/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vrs;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import config.dbConnector;
import java.util.ArrayList;

/**
 *
 * @author ROCO
 */
public class v_clients extends javax.swing.JInternalFrame {

    /**
     * Creates new form v_clients
     */
    public v_clients() {
        initComponents();
        // Set up search and refresh actions
        btnSearch.addActionListener(e -> loadClientCards(txtSearch.getText()));
        txtSearch.addActionListener(e -> loadClientCards(txtSearch.getText()));
        btnRefresh.addActionListener(e -> {
            txtSearch.setText("");
            loadClientCards("");
        });
        // Load cards on startup
        loadClientCards("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        topPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        middlePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        clientsContainer = new javax.swing.JPanel();
        bottomPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        mainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        topPanel.setBackground(new java.awt.Color(110, 0, 0));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CLIENTS HISTORY");

        btnSearch.setText("Search");

        btnRefresh.setText("Refresh");

        javax.swing.GroupLayout topPanelLayout = new javax.swing.GroupLayout(topPanel);
        topPanel.setLayout(topPanelLayout);
        topPanelLayout.setHorizontalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh)
                .addGap(79, 79, 79))
        );
        topPanelLayout.setVerticalGroup(
            topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(btnRefresh)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        mainPanel.add(topPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, 0, 930, 90));

        middlePanel.setBackground(new java.awt.Color(110, 20, 0));

        clientsContainer.setBackground(new java.awt.Color(110, 5, 0));

        javax.swing.GroupLayout clientsContainerLayout = new javax.swing.GroupLayout(clientsContainer);
        clientsContainer.setLayout(clientsContainerLayout);
        clientsContainerLayout.setHorizontalGroup(
            clientsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 928, Short.MAX_VALUE)
        );
        clientsContainerLayout.setVerticalGroup(
            clientsContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 308, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(clientsContainer);

        javax.swing.GroupLayout middlePanelLayout = new javax.swing.GroupLayout(middlePanel);
        middlePanel.setLayout(middlePanelLayout);
        middlePanelLayout.setHorizontalGroup(
            middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        middlePanelLayout.setVerticalGroup(
            middlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        mainPanel.add(middlePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 930, 310));

        bottomPanel.setBackground(new java.awt.Color(110, 0, 20));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("NAME:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("PHONE NUMBER:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ADDRESS");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("EMAIL ADDRESS:");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Rented Vehicle:");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Amount:");

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Start Date:");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("End Date:");

        javax.swing.GroupLayout bottomPanelLayout = new javax.swing.GroupLayout(bottomPanel);
        bottomPanel.setLayout(bottomPanelLayout);
        bottomPanelLayout.setHorizontalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bottomPanelLayout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bottomPanelLayout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bottomPanelLayout.createSequentialGroup()
                        .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(bottomPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(bottomPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(bottomPanelLayout.createSequentialGroup()
                        .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(194, Short.MAX_VALUE))
            .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bottomPanelLayout.createSequentialGroup()
                    .addGap(300, 300, 300)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(492, Short.MAX_VALUE)))
        );
        bottomPanelLayout.setVerticalGroup(
            bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bottomPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bottomPanelLayout.createSequentialGroup()
                        .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(5, 5, 5)
                        .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addGap(3, 3, 3)
                        .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel10))
                        .addGap(4, 4, 4)
                        .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 61, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(bottomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottomPanelLayout.createSequentialGroup()
                    .addContainerGap(242, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(28, 28, 28)))
        );

        mainPanel.add(bottomPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 400, 930, 270));

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadClientCards(String searchText) {
        try {
            clientsContainer.removeAll();
            clientsContainer.setLayout(new GridLayout(0, 2, 15, 15));
            clientsContainer.setBackground(new Color(240, 240, 240));

            Connection con = new dbConnector().getConnection();
            String query = "SELECT c.*, r.*, v.v_make, v.v_model, v.v_plate " +
                           "FROM tbl_clients c " +
                           "LEFT JOIN tbl_rentals r ON c.c_id = r.r_client_id " +
                          "LEFT JOIN tbl_vehicles v ON r.r_vehicle_id = v.v_id " +
                          "WHERE LOWER(c.c_name) LIKE ? OR LOWER(c.c_phone) LIKE ? OR LOWER(c.c_email) LIKE ? " +
                          "ORDER BY r.r_start_date DESC";
            
            PreparedStatement pst = con.prepareStatement(query);
            String searchPattern = "%" + searchText.toLowerCase() + "%";
            pst.setString(1, searchPattern);
            pst.setString(2, searchPattern);
            pst.setString(3, searchPattern);
            
            ResultSet rs = pst.executeQuery();
            boolean hasResults = false;
            
            while (rs.next()) {
                hasResults = true;
                final int clientId = rs.getInt("c_id");
                final String name = rs.getString("c_name");
                final String phone = rs.getString("c_phone");
                final String email = rs.getString("c_email");
                final String address = rs.getString("c_address");
                final byte[] imageData = rs.getBytes("c_image");
                
                // Create main card panel
                JPanel cardPanel = new JPanel();
                cardPanel.setLayout(new BorderLayout(0, 0));
                cardPanel.setPreferredSize(new Dimension(450, 500));
                cardPanel.setBackground(Color.WHITE);
                cardPanel.setBorder(BorderFactory.createCompoundBorder(
                    BorderFactory.createLineBorder(new Color(200, 200, 200), 1),
                    BorderFactory.createEmptyBorder(15, 15, 15, 15)
                ));

                // Client info panel (top)
                JPanel infoPanel = new JPanel();
                infoPanel.setLayout(new BoxLayout(infoPanel, BoxLayout.Y_AXIS));
                infoPanel.setBackground(Color.WHITE);
                infoPanel.setBorder(BorderFactory.createEmptyBorder(0, 0, 10, 0));

                // Client image and name
                JPanel headerPanel = new JPanel(new BorderLayout(10, 0));
                headerPanel.setBackground(Color.WHITE);
                
                JLabel imageLabel = new JLabel();
                imageLabel.setPreferredSize(new Dimension(80, 80));
                if (imageData != null && imageData.length > 0) {
                    ImageIcon imageIcon = new ImageIcon(imageData);
                    Image img = imageIcon.getImage().getScaledInstance(80, 80, Image.SCALE_SMOOTH);
                    imageLabel.setIcon(new ImageIcon(img));
                } else {
                    imageLabel.setText("No Image");
                    imageLabel.setFont(new Font("Tahoma", Font.ITALIC, 12));
                    imageLabel.setForeground(Color.GRAY);
                    imageLabel.setHorizontalAlignment(JLabel.CENTER);
                }
                
                JLabel nameLabel = new JLabel(name);
                nameLabel.setFont(new Font("Tahoma", Font.BOLD, 18));
                headerPanel.add(imageLabel, BorderLayout.WEST);
                headerPanel.add(nameLabel, BorderLayout.CENTER);
                infoPanel.add(headerPanel);
                infoPanel.add(Box.createVerticalStrut(15));

                // Contact info
                JPanel contactPanel = new JPanel();
                contactPanel.setLayout(new BoxLayout(contactPanel, BoxLayout.Y_AXIS));
                contactPanel.setBackground(Color.WHITE);
                
                addInfoRow(contactPanel, "Phone:", phone);
                addInfoRow(contactPanel, "Email:", email);
                addInfoRow(contactPanel, "Address:", address);
                
                infoPanel.add(contactPanel);
                cardPanel.add(infoPanel, BorderLayout.NORTH);

                // Rental history panel (bottom)
                JPanel historyPanel = new JPanel();
                historyPanel.setLayout(new BoxLayout(historyPanel, BoxLayout.Y_AXIS));
                historyPanel.setBackground(new Color(245, 245, 245));
                historyPanel.setBorder(BorderFactory.createEmptyBorder(10, 10, 10, 10));

                JLabel historyTitle = new JLabel("Rental History");
                historyTitle.setFont(new Font("Tahoma", Font.BOLD, 16));
                historyTitle.setAlignmentX(Component.LEFT_ALIGNMENT);
                historyPanel.add(historyTitle);
                historyPanel.add(Box.createVerticalStrut(10));

                // Get rental history
                String rentalQuery = "SELECT r.*, v.v_make, v.v_model, v.v_plate " +
                                   "FROM tbl_rentals r " +
                                   "JOIN tbl_vehicles v ON r.r_vehicle_id = v.v_id " +
                                   "WHERE r.r_client_id = ? " +
                                   "ORDER BY r.r_start_date DESC";
                PreparedStatement rentalStmt = con.prepareStatement(rentalQuery);
                rentalStmt.setInt(1, clientId);
                ResultSet rentalRs = rentalStmt.executeQuery();

                boolean hasRentals = false;
                while (rentalRs.next()) {
                    hasRentals = true;
                    String vehicle = rentalRs.getString("v_make") + " " + rentalRs.getString("v_model");
                    String plate = rentalRs.getString("v_plate");
                    String startDate = rentalRs.getString("r_start_date");
                    String endDate = rentalRs.getString("r_end_date");
                    double amount = rentalRs.getDouble("r_total_amount");
                    String status = rentalRs.getString("r_status");

                    JPanel rentalPanel = createRentalPanel(vehicle, plate, startDate, endDate, amount, status);
                    historyPanel.add(rentalPanel);
                    historyPanel.add(Box.createVerticalStrut(10));
                }

                if (!hasRentals) {
                    JLabel noRentalsLabel = new JLabel("No rental history");
                    noRentalsLabel.setFont(new Font("Tahoma", Font.ITALIC, 14));
                    noRentalsLabel.setForeground(Color.GRAY);
                    noRentalsLabel.setAlignmentX(Component.LEFT_ALIGNMENT);
                    historyPanel.add(noRentalsLabel);
                }

                cardPanel.add(historyPanel, BorderLayout.CENTER);

                // Add hover effect
                cardPanel.addMouseListener(new java.awt.event.MouseAdapter() {
                    public void mouseEntered(java.awt.event.MouseEvent evt) {
                        if (cardPanel != selectedCard) {
                            cardPanel.setBorder(BorderFactory.createCompoundBorder(
                                BorderFactory.createLineBorder(new Color(0, 100, 200), 2),
                                BorderFactory.createEmptyBorder(14, 14, 14, 14)
                            ));
                        }
                    }

                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        if (cardPanel != selectedCard) {
                            cardPanel.setBorder(BorderFactory.createCompoundBorder(
                                BorderFactory.createLineBorder(new Color(200, 200, 200), 1),
                                BorderFactory.createEmptyBorder(15, 15, 15, 15)
                            ));
                        }
                    }

                    public void mouseClicked(java.awt.event.MouseEvent evt) {
                        selectClientCard(cardPanel, clientId, name, phone, email, address, imageData);
                    }
                });

                clientsContainer.add(cardPanel);
            }

            if (!hasResults) {
                JPanel noResultsPanel = new JPanel();
                noResultsPanel.setLayout(new FlowLayout(FlowLayout.CENTER));
                noResultsPanel.setBackground(new Color(240, 240, 240));
                
                JLabel noResultsLabel = new JLabel("No clients found matching your search");
                noResultsLabel.setFont(new Font("Tahoma", Font.BOLD, 16));
                noResultsLabel.setForeground(new Color(100, 100, 100));
                noResultsPanel.add(noResultsLabel);
                
                clientsContainer.add(noResultsPanel);
                clientsContainer.add(new JPanel());
            }

            clientsContainer.revalidate();
            clientsContainer.repaint();
            
            rs.close();
            pst.close();
            con.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error loading client data: " + e.getMessage(),
                "Database Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void addInfoRow(JPanel panel, String label, String value) {
        JPanel rowPanel = new JPanel(new BorderLayout(10, 0));
        rowPanel.setBackground(Color.WHITE);
        
        JLabel labelComponent = new JLabel(label);
        labelComponent.setFont(new Font("Tahoma", Font.BOLD, 12));
        labelComponent.setForeground(new Color(100, 100, 100));
        
        JLabel valueComponent = new JLabel(value);
        valueComponent.setFont(new Font("Tahoma", Font.PLAIN, 12));
        
        rowPanel.add(labelComponent, BorderLayout.WEST);
        rowPanel.add(valueComponent, BorderLayout.CENTER);
        panel.add(rowPanel);
        panel.add(Box.createVerticalStrut(5));
    }

    private JPanel createRentalPanel(String vehicle, String plate, String startDate, String endDate, double amount, String status) {
        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));
        panel.setBackground(Color.WHITE);
        panel.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(220, 220, 220), 1),
            BorderFactory.createEmptyBorder(10, 10, 10, 10)
        ));

        // Vehicle info
        JLabel vehicleLabel = new JLabel(vehicle + " (" + plate + ")");
        vehicleLabel.setFont(new Font("Tahoma", Font.BOLD, 14));
        vehicleLabel.setAlignmentX(Component.LEFT_ALIGNMENT);
        panel.add(vehicleLabel);
        panel.add(Box.createVerticalStrut(5));

        // Dates
        JLabel datesLabel = new JLabel(startDate + " to " + endDate);
        datesLabel.setFont(new Font("Tahoma", Font.PLAIN, 12));
        datesLabel.setForeground(new Color(100, 100, 100));
        datesLabel.setAlignmentX(Component.LEFT_ALIGNMENT);
        panel.add(datesLabel);
        panel.add(Box.createVerticalStrut(5));

        // Amount and status
        JPanel bottomPanel = new JPanel(new BorderLayout());
        bottomPanel.setBackground(Color.WHITE);
        
        JLabel amountLabel = new JLabel(String.format("₱%.2f", amount));
        amountLabel.setFont(new Font("Tahoma", Font.BOLD, 14));
        amountLabel.setForeground(new Color(0, 100, 0));
        
        JLabel statusLabel = new JLabel(status.toUpperCase());
        statusLabel.setFont(new Font("Tahoma", Font.BOLD, 12));
        statusLabel.setForeground(Color.WHITE);
        statusLabel.setBorder(BorderFactory.createEmptyBorder(3, 8, 3, 8));
        
        // Set status color
        Color statusColor;
        if (status.equalsIgnoreCase("active")) {
            statusColor = new Color(0, 150, 0); // Green
        } else if (status.equalsIgnoreCase("completed")) {
            statusColor = new Color(100, 100, 100); // Gray
        } else if (status.equalsIgnoreCase("cancelled")) {
            statusColor = new Color(200, 0, 0); // Red
        } else {
            statusColor = new Color(100, 100, 100); // Default gray
        }
        statusLabel.setBackground(statusColor);
        statusLabel.setOpaque(true);
        
        bottomPanel.add(amountLabel, BorderLayout.WEST);
        bottomPanel.add(statusLabel, BorderLayout.EAST);
        
        panel.add(bottomPanel);

        return panel;
    }

    private void selectClientCard(JPanel cardPanel, int clientId, String name, String phone, 
                                String email, String address, byte[] imageData) {
        // Reset previously selected card
        if (selectedCard != null) {
            selectedCard.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(200, 200, 200), 1),
                BorderFactory.createEmptyBorder(15, 15, 15, 15)
            ));
        }
        
        // Update selected card
        selectedCard = cardPanel;
        cardPanel.setBorder(BorderFactory.createCompoundBorder(
            BorderFactory.createLineBorder(new Color(0, 100, 200), 3),
            BorderFactory.createEmptyBorder(13, 13, 13, 13)
        ));
        
        // Update bottom panel fields
        jTextField1.setText(name);
        jTextField2.setText(phone);
        jTextField3.setText(email);
        jTextField4.setText(address);
        
        // Update client image
        if (imageData != null && imageData.length > 0) {
            ImageIcon imageIcon = new ImageIcon(imageData);
            Image img = imageIcon.getImage().getScaledInstance(200, 200, Image.SCALE_SMOOTH);
            jLabel2.setIcon(new ImageIcon(img));
        } else {
            jLabel2.setIcon(null);
            jLabel2.setText("No Image");
        }
        
        // Load rental details
        try {
            Connection con = new dbConnector().getConnection();
            String query = "SELECT r.*, v.v_make, v.v_model, v.v_plate, " +
                          "DATE_FORMAT(r.r_start_date, '%Y-%m-%d') as formatted_start_date, " +
                          "DATE_FORMAT(r.r_end_date, '%Y-%m-%d') as formatted_end_date " +
                          "FROM tbl_rentals r " +
                          "JOIN tbl_vehicles v ON r.r_vehicle_id = v.v_id " +
                          "WHERE r.r_client_id = ? " +
                          "ORDER BY r.r_start_date DESC LIMIT 1";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setInt(1, clientId);
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                String vehicle = rs.getString("v_make") + " " + rs.getString("v_model");
                String plate = rs.getString("v_plate");
                String startDate = rs.getString("formatted_start_date");
                String endDate = rs.getString("formatted_end_date");
                double amount = rs.getDouble("r_total_amount");
                
                jTextField5.setText(vehicle + " (" + plate + ")");
                jTextField6.setText(String.format("₱%.2f", amount));
                jTextField7.setText(startDate != null ? startDate : "");
                jTextField8.setText(endDate != null ? endDate : "");
            } else {
                jTextField5.setText("No rental");
                jTextField6.setText("");
                jTextField7.setText("");
                jTextField8.setText("");
            }
            
            rs.close();
            pst.close();
            con.close();
        } catch (SQLException e) {
            System.err.println("Error loading rental details: " + e.getMessage());
            JOptionPane.showMessageDialog(this, 
                "Error loading rental details: " + e.getMessage(),
                "Database Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bottomPanel;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JPanel clientsContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel middlePanel;
    private javax.swing.JPanel topPanel;
    private javax.swing.JTextField txtSearch;
    private JPanel selectedCard = null;
    // End of variables declaration//GEN-END:variables
}
